name: JMeter Test Run
'on':
  push:
    branches:
      - main
  pull_request: null
jobs:
  jmeter-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
      - name: Download Apache JMeter
        run: >
          wget
          https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.5.tgz

          tar -xzf apache-jmeter-5.5.tgz

          echo "JMETER_HOME=$(pwd)/apache-jmeter-5.5" >> $GITHUB_ENV
      - name: Run JMeter test plan
        run: |
          $JMETER_HOME/bin/jmeter -n -t your-test-plan.jmx -l results.jtl
      - name: Upload test results artifact
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: results.jtl
